// ============================================================
// bank_model.dart
// Represents a bank account added by the user.
// e.g., SBI Savings, HDFC Salary Account
// ============================================================

class BankModel {
  final String id;              // Unique ID (generated by uuid package)
  final String name;            // e.g., "SBI", "HDFC", "IDBI"
  final String accountType;     // e.g., "Savings", "Current", "Salary"
  final double openingBalance;  // Balance when the account was added
  final double currentBalance;  // Live balance (updated on each transaction)
  final DateTime dateAdded;     // Date the account was added to the app
  final String ownerName;       // The user's name (shown on the card)

  const BankModel({
    required this.id,
    required this.name,
    required this.accountType,
    required this.openingBalance,
    required this.currentBalance,
    required this.dateAdded,
    required this.ownerName,
  });

  // Convert to Map for JSON storage
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'account_type': accountType,
      'opening_balance': openingBalance,
      'current_balance': currentBalance,
      // We store dates as ISO strings (e.g., "2026-07-06")
      'date_added': dateAdded.toIso8601String(),
      'owner_name': ownerName,
    };
  }

  // Create from Map (when loading from storage)
  factory BankModel.fromMap(Map<String, dynamic> map) {
    return BankModel(
      id: map['id'] as String,
      name: map['name'] as String,
      accountType: map['account_type'] as String,
      openingBalance: (map['opening_balance'] as num).toDouble(),
      currentBalance: (map['current_balance'] as num).toDouble(),
      dateAdded: DateTime.parse(map['date_added'] as String),
      ownerName: map['owner_name'] as String? ?? '',
    );
  }

  /// Creates a copy with some fields updated
  BankModel copyWith({
    String? id,
    String? name,
    String? accountType,
    double? openingBalance,
    double? currentBalance,
    DateTime? dateAdded,
    String? ownerName,
  }) {
    return BankModel(
      id: id ?? this.id,
      name: name ?? this.name,
      accountType: accountType ?? this.accountType,
      openingBalance: openingBalance ?? this.openingBalance,
      currentBalance: currentBalance ?? this.currentBalance,
      dateAdded: dateAdded ?? this.dateAdded,
      ownerName: ownerName ?? this.ownerName,
    );
  }

  /// Full display name: "SBI (Savings)"
  String get displayName => '$name ($accountType)';

  @override
  String toString() => 'BankModel(id: $id, name: $name, balance: $currentBalance)';
}
